### ISSUE TITLE
Composite templates need to make sure the widget types are registered

### ISSUE THREAD

**Issue by alatiera** [gtk-rs/gtk-rs#238]
(Haven't tried reproducing this against gtk3 bindings, was playing around with gtk4-rs so  far)

I was trying to do something like this, with its respective subclass implementation. But when trying to create the object it blows up . Manually registering the types of the its children made it work though.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<interface>
  <requires lib="gtk" version="4.0"/>
  <template class="ExampleApplicationWindow" parent="GtkApplicationWindow">
    <property name="decorated">True</property>
    <property name="default_width">600</property>
    <property name="default_height">400</property>
    <property name="icon_name">@app-id@</property>
    <child type="titlebar">
      <object class="GtkBox">
        <property name="visible">False</property>
      </object>
    </child>
    <child>
      <object class="GtkOverlay" id="overlay">
        <child type="overlay">
          <object class="ExampleHeaderBox" id="headerbox">
          </object>
        </child>
        <child type="overlay">
          <object class="ExamplePlayerControls" id="controls">
          </object>
        </child>
      </object>
    </child>
  </template>
</interface>
```

```
willberenamed:2): Gtk-CRITICAL **: 09:13:29.552: Error building template class 'ExampleApplicationWindow' for an instance of type 'ExampleApplicationWindow': .:0:0 Invalid object type 'ExampleHeaderBox'
thread 'main' panicked at 'Failed to retrieve template child. Please check that it has been bound.', src/window.rs:65:22
stack backtrace:
   0: rust_begin_unwind
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:483
   1: core::panicking::panic_fmt
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/panicking.rs:85
   2: core::option::expect_failed
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/option.rs:1226
   3: core::option::Option<T>::expect
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/option.rs:346
   4: gtk4::subclass::widget::TemplateChild<T>::get
             at ./Projects/willberenamed/_build/target/cargo-home/git/checkouts/gtk4-rs-e74ad56283dfeb5e/bfae73f/gtk4/src/subclass/widget.rs:990
   5: <willberenamed::window::ExampleApplicationWindowPrivate as glib::subclass::object::ObjectImpl>::constructed
             at ./Projects/willberenamed/src/window.rs:65
   6: glib::subclass::object::constructed
             at ./Projects/willberenamed/_build/target/cargo-home/git/checkouts/gtk-rs-48ef14c1f17c79fb/5bef67e/glib/src/subclass/object.rs:98
   7: <unknown>
   8: g_object_newv
   9: glib::object::Object::new_internal
             at ./Projects/willberenamed/_build/target/cargo-home/git/checkouts/gtk-rs-48ef14c1f17c79fb/5bef67e/glib/src/object.rs:1165
  10: glib::object::Object::with_type
             at ./Projects/willberenamed/_build/target/cargo-home/git/checkouts/gtk-rs-48ef14c1f17c79fb/5bef67e/glib/src/object.rs:1105
  11: glib::object::Object::new
             at ./Projects/willberenamed/_build/target/cargo-home/git/checkouts/gtk-rs-48ef14c1f17c79fb/5bef67e/glib/src/object.rs:1074
  12: willberenamed::window::ExampleApplicationWindow::new
             at ./Projects/willberenamed/src/window.rs:99
  13: <willberenamed::application::ExampleApplicationPrivate as gio::subclass::application::ApplicationImpl>::activate
             at ./Projects/willberenamed/src/application.rs:62
  14: gio::subclass::application::application_activate
             at ./Projects/willberenamed/_build/target/cargo-home/git/checkouts/gtk-rs-48ef14c1f17c79fb/5bef67e/gio/src/subclass/application.rs:368
  15: <unknown>
  16: g_signal_emit_valist
  17: g_signal_emit
  18: <unknown>
  19: <T as gio::subclass::application::ApplicationImplExt>::parent_local_command_line
             at ./Projects/willberenamed/_build/target/cargo-home/git/checkouts/gtk-rs-48ef14c1f17c79fb/5bef67e/gio/src/subclass/application.rs:232
  20: gio::subclass::application::ApplicationImpl::local_command_line
             at ./Projects/willberenamed/_build/target/cargo-home/git/checkouts/gtk-rs-48ef14c1f17c79fb/5bef67e/gio/src/subclass/application.rs:99
  21: gio::subclass::application::application_local_command_line
             at ./Projects/willberenamed/_build/target/cargo-home/git/checkouts/gtk-rs-48ef14c1f17c79fb/5bef67e/gio/src/subclass/application.rs:411
  22: g_application_run
  23: <O as gio::application::ApplicationExtManual>::run
             at ./Projects/willberenamed/_build/target/cargo-home/git/checkouts/gtk-rs-48ef14c1f17c79fb/5bef67e/gio/src/application.rs:22
  24: willberenamed::application::ExampleApplication::run
             at ./Projects/willberenamed/src/application.rs:179
  25: willberenamed::main
             at ./Projects/willberenamed/src/main.rs:37
  26: core::ops::function::FnOnce::call_once
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/ops/function.rs:227
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Application exited
```

Workaround:
```diff
diff --git src/application.rs src/application.rs
index 6b94db4..407990d 100644
--- src/application.rs
+++ src/application.rs
@@ -13,6 +13,8 @@ use once_cell::sync::OnceCell;
 
 use crate::config::*;
 use crate::window::ExampleApplicationWindow;
+use crate::headerbox::ExampleHeaderBox;
+use crate::player_controls::ExamplePlayerControls;
 
 #[derive(Debug)]
 pub struct ExampleApplicationPrivate {
@@ -57,6 +59,8 @@ impl gio::subclass::prelude::ApplicationImpl for ExampleApplicationPrivate {
 
         app.setup_css();
 
+        ExampleHeaderBox::static_type();
+        ExamplePlayerControls::static_type();
         let window = ExampleApplicationWindow::new(app);
         self.window
             .set(window.downgrade())
```

**Comment by alatiera** [comment]
Actually, I am not sure if this is expected behavior or not, haven't tried reproducing with C code. Its possible you are expected to register your types yourself.

**Comment by sdroege** [comment]
Yes you're expected to do that in C with `g_type_ensure()`, which is basically the same as our `Foo::static_type()` functions.

I think there's a PR or issue about this for gtk4-rs already.

**Comment by alatiera** [comment]
Indeed 

/duplicate https://github.com/gtk-rs/gtk4-rs/issues/116
