### ISSUE TITLE
Crash after moving TextView to new container

### ISSUE THREAD

**Issue by nicholasbishop** [gtk-rs/gtk-rs#277]
Minimal example:

```rust
use gio::prelude::*;
use gtk::prelude::*;

fn build_ui(application: &gtk::Application) {
    let window = gtk::ApplicationWindow::new(application);
    let view = gtk::TextView::new();

    {
        let container = gtk::Box::new(gtk::Orientation::Horizontal, 1);
        container.add(&view);
        window.add(&container);

        window.remove(&container);
    }

    {
        let container = gtk::Box::new(gtk::Orientation::Horizontal, 1);
        container.add(&view);
        window.add(&container);
    }

    window.show_all();
}

fn main() {
    let application = gtk::Application::new(None, Default::default()).unwrap();

    application.connect_activate(|app| {
        build_ui(app);
    });

    application.run(&std::env::args().collect::<Vec<_>>());
}
```

```toml
[dependencies]
gio = "0.9"
gtk = "0.9"
```

This minimal example looks somewhat nonsensical, but in the original program I have some `TextView`s in a layout that dynamically changes, so I need to delete or add `Box`es and move the `TextView`s between them as needed.

Changing the `TextView` to a `Button` in this example no longer crashes.

Backtrace:

```
#0  0x00007ffff7b449f9 in _gtk_pixel_cache_set_extra_size
    (extra_width=64, extra_height=0, cache=0x0) at gtkpixelcache.c:98
#1  gtk_text_view_size_allocate (widget=0x5555558e0300, allocation=0x7fffffffc180)
    at gtktextview.c:4281
#2  0x00007ffff7ba5de9 in gtk_widget_size_allocate_with_baseline
    (widget=0x5555558e0300, allocation=<optimized out>, baseline=<optimized out>)
    at gtkwidget.c:6175
#3  0x00007ffff792fa0a in gtk_box_size_allocate_no_center
    (widget=<optimized out>, allocation=0x7fffffffc4e0) at gtkbox.c:817
#4  0x00007ffff793099c in gtk_box_allocate_contents
    (gadget=<optimized out>, allocation=<optimized out>, baseline=<optimized out>, out_clip=0x7fffffffc4c0, unused=<optimized out>) at gtkbox.c:1211
#5  0x00007ffff7988328 in gtk_css_gadget_allocate
    (gadget=<optimized out>, allocation=0x7fffffffc630, baseline=-1, out_clip=0x7fffffffc560) at gtkcssgadget.c:790
#6  0x00007ffff7930a19 in gtk_box_size_allocate
    (widget=0x5555558e2310, allocation=0x7fffffffc630) at gtkbox.c:1225
#7  0x00007ffff7ba5de9 in gtk_widget_size_allocate_with_baseline
    (widget=0x5555558e2310, allocation=<optimized out>, baseline=<optimized out>)
    at gtkwidget.c:6175
#8  0x00007ffff7bc3e3b in gtk_window_size_allocate
    (widget=0x5555558d62a0, allocation=<optimized out>) at gtkwindow.c:7921
#9  0x00007ffff7ba5de9 in gtk_widget_size_allocate_with_baseline
    (widget=0x5555558d62a0, allocation=<optimized out>, baseline=<optimized out>)
    at gtkwidget.c:6175
#10 0x00007ffff7bc2fba in gtk_window_realize (widget=0x5555558d62a0)
    at gtkwindow.c:7424
#11 0x00007ffff791ff84 in gtk_application_window_real_realize
    (widget=0x5555558d62a0) at gtkapplicationwindow.c:681
#12 0x00007ffff733fe2a in g_closure_invoke () at /lib64/libgobject-2.0.so.0
#13 0x00007ffff7368f0a in signal_emit_unlocked_R.isra.0 ()
    at /lib64/libgobject-2.0.so.0
#14 0x00007ffff735cf82 in g_signal_emit_valist () at /lib64/libgobject-2.0.so.0
#15 0x00007ffff735d1a3 in g_signal_emit () at /lib64/libgobject-2.0.so.0
#16 0x00007ffff7ba4ad7 in gtk_widget_realize (widget=0x5555558d62a0)
    at gtkwidget.c:5519
#17 0x00007ffff7bc46cf in gtk_window_show (widget=0x5555558d62a0)
    at gtkwindow.c:6181
#18 0x00007ffff733fe2a in g_closure_invoke () at /lib64/libgobject-2.0.so.0
#19 0x00007ffff7368f0a in signal_emit_unlocked_R.isra.0 ()
    at /lib64/libgobject-2.0.so.0
#20 0x00007ffff735cf82 in g_signal_emit_valist () at /lib64/libgobject-2.0.so.0
#21 0x00007ffff735d1a3 in g_signal_emit () at /lib64/libgobject-2.0.so.0
#22 0x00007ffff7ba5476 in gtk_widget_show (widget=0x5555558d62a0)
    at gtkwidget.c:4848
#23 0x000055555555eacf in gtk::auto::widget::{{impl}}::show_all<gtk::auto::application_window::ApplicationWindow> (self=0x7fffffffd260)
    at /home/nbishop/.cargo/registry/src/github.com-1ecc6299db9ec823/gtk-0.9.2/src/auto/widget.rs:2708
#24 0x000055555555ed0f in gtk_crash::build_ui (application=0x7fffffffd2f8)
    at src/main.rs:22
#25 0x000055555555d7f6 in gtk_crash::main::{{closure}} (app=0x7fffffffd2f8)
    at src/main.rs:29
#26 0x000055555555e8ce in gio::auto::application::{{impl}}::connect_activate::activate_trampoline<gtk::auto::application::Application,closure-0>
    (this=0x5555555f50f0, f=0x1)
    at /home/nbishop/.cargo/registry/src/github.com-1ecc6299db9ec823/gio-0.9.1/src/auto/application.rs:559
#27 0x00007ffff733fe2a in g_closure_invoke () at /lib64/libgobject-2.0.so.0
#28 0x00007ffff7369273 in signal_emit_unlocked_R.isra.0 ()
    at /lib64/libgobject-2.0.so.0
#29 0x00007ffff735cf82 in g_signal_emit_valist () at /lib64/libgobject-2.0.so.0
#30 0x00007ffff735d1a3 in g_signal_emit () at /lib64/libgobject-2.0.so.0
#31 0x00007ffff7461a68 in g_application_real_local_command_line ()
    at /lib64/libgio-2.0.so.0
#32 0x00007ffff7461c46 in g_application_run () at /lib64/libgio-2.0.so.0
#33 0x000055555555dc53 in gio::application::{{impl}}::run<gtk::auto::application::Application> (self=0x7fffffffd8f0, argv=...)
    at /home/nbishop/.cargo/registry/src/github.com-1ecc6299db9ec823/gio-0.9.1/src/application.rs:23
#34 0x000055555555ee54 in gtk_crash::main () at src/main.rs:32
```

**Comment by sdroege** [comment]
Also crashes in C with GTK3 but not with GTK4

GTK3:
```cpp
#include <gtk/gtk.h>

static void
build_ui (GtkApplication * app)
{
  GtkWidget *window = gtk_application_window_new (app);
  GtkWidget *view = gtk_text_view_new ();

  g_object_ref_sink (view);

  {
    GtkWidget *container = gtk_box_new (GTK_ORIENTATION_HORIZONTAL, 1);


    gtk_container_add (GTK_CONTAINER (container), view);
    gtk_container_add (GTK_CONTAINER (window), container);
    gtk_container_remove (GTK_CONTAINER (window), container);
  }

  {
    GtkWidget *container = gtk_box_new (GTK_ORIENTATION_HORIZONTAL, 1);


    gtk_container_add (GTK_CONTAINER (container), view);
    gtk_container_add (GTK_CONTAINER (window), container);
  }

  g_object_unref (view);

  gtk_widget_show_all (window);
}

int
main (int argc, char *argv[])
{
  GtkApplication *app = gtk_application_new (NULL, G_APPLICATION_FLAGS_NONE);
  g_signal_connect (app, "activate", G_CALLBACK (build_ui), NULL);
  return g_application_run (G_APPLICATION (app), argc, argv);
}
```

GTK4:
```cpp
#include <gtk/gtk.h>

static void
build_ui (GtkApplication * app)
{
  GtkWidget *window = gtk_application_window_new (app);
  GtkWidget *view = gtk_text_view_new ();

  g_object_ref_sink (view);

  {
    GtkWidget *container = gtk_box_new (GTK_ORIENTATION_HORIZONTAL, 1);


    gtk_box_append (GTK_BOX (container), view);
    gtk_window_set_child (GTK_WINDOW (window), container);
    gtk_window_set_child (GTK_WINDOW (window), NULL);
  }

  {
    GtkWidget *container = gtk_box_new (GTK_ORIENTATION_HORIZONTAL, 1);


    gtk_box_append (GTK_BOX (container), view);
    gtk_window_set_child (GTK_WINDOW (window), container);
  }

  g_object_unref (view);

  gtk_window_present (GTK_WINDOW (window));
}

int
main (int argc, char *argv[])
{
  GtkApplication *app = gtk_application_new (NULL, G_APPLICATION_FLAGS_NONE);
  g_signal_connect (app, "activate", G_CALLBACK (build_ui), NULL);
  return g_application_run (G_APPLICATION (app), argc, argv);
}
```

**Comment by sdroege** [comment]
See https://gitlab.gnome.org/GNOME/gtk/-/issues/3628

**Comment by nicholasbishop** [comment]
Thank you for checking into it and forwarding the issue.
